version: "2.1"

services:
  
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=giteauser
      - DB_PASSWD="p@ssw0rd="
    restart: always
    networks:
      - main_network
    volumes:
      - data_gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
       - "3000:3000"
       - "222:22"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: gitea_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=testertester78
#      - MYSQL_USER=admin
#      - MYSQL_PASSWORD=superpassword
#      - MYSQL_DATABASE=nextcloud
    networks:
      - main_network
    volumes:
      - mysql_gitea:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "3306:3306"
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -uroot --password=$$MYSQL_PASSWORD
        timeout: 20s
        retries: 10

#  adminer:
#    image: adminer:latest
#    container_name: adminer
#    restart: always
#    networks:
#      - main_network
#    ports:
#      - "3128:8080"
#    depends_on:
#      - db

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    networks:
      - main_network
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - nextcloud:/var/www/html

volumes:
  data_gitea:
  mysql_gitea:
  nextcloud:

networks:
  main_network:

